services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - SERVER_NAME=:8080
#      - FRANKENPHP_CONFIG="worker /app/public/index.php"
    depends_on:
      - redis
    volumes:
      - ./index.php:/app/public/index.php
      - ../src:/app/src
      - ../vendor:/app/vendor
      - ./Caddyfile:/etc/frankenphp/Caddyfile

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
